// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: scheme.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GpgkServiceClient is the client API for GpgkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GpgkServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type gpgkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGpgkServiceClient(cc grpc.ClientConnInterface) GpgkServiceClient {
	return &gpgkServiceClient{cc}
}

func (c *gpgkServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, "/gpgk.GpgkService/Execute", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GpgkServiceServer is the server API for GpgkService service.
// All implementations must embed UnimplementedGpgkServiceServer
// for forward compatibility
type GpgkServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedGpgkServiceServer()
}

// UnimplementedGpgkServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGpgkServiceServer struct {
}

func (UnimplementedGpgkServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedGpgkServiceServer) mustEmbedUnimplementedGpgkServiceServer() {}

// UnsafeGpgkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GpgkServiceServer will
// result in compilation errors.
type UnsafeGpgkServiceServer interface {
	mustEmbedUnimplementedGpgkServiceServer()
}

func RegisterGpgkServiceServer(s grpc.ServiceRegistrar, srv GpgkServiceServer) {
	s.RegisterService(&GpgkService_ServiceDesc, srv)
}

func _GpgkService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GpgkServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gpgk.GpgkService/Execute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GpgkServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GpgkService_ServiceDesc is the grpc.ServiceDesc for GpgkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GpgkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gpgk.GpgkService",
	HandlerType: (*GpgkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _GpgkService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scheme.proto",
}
